steps:
  # build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/github.com/ujihisa/phoenix-hello', '.']
  # push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/github.com/ujihisa/phoenix-hello']
  # Deploy container image to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta', 'run', 'deploy', 'phoenix-hello', '--image', 'gcr.io/$PROJECT_ID/github.com/ujihisa/phoenix-hello', '--region', 'us-central1', '--allow-unauthenticated', '--platform', 'managed']
images:
- gcr.io/$PROJECT_ID/github.com/ujihisa/phoenix-hello
